version: "3.8"

services:
  quilt-server:
    build: 
      context: .
      args:
        MINECRAFT_VERSION: "1.20.1"
    volumes:
      # Needs Z on Fedora because of SELinux, see 
      # <https://docs.podman.io/en/latest/markdown/podman-run.1.html#volume-v-source-volume-host-dir-container-dir-options>
      # Labeling Volume Mounts

      # Configuration
      ## Ideally we don't want the server to write to this,
      ## only should be able to change this outside
      - ./data/eula.txt:/data/eula.txt:ro,Z

      ## This can safely be set to readonly, but you will get an error
      ## saying "Failed to store properties to file: server.properties"
      ## By default, went with rw so this error doesn't pop up
      - ./data/server.properties:/data/server.properties:rw,Z

      ## Mods will add new config files here so they need to be able to write.
      ## This can be set to readonly once you've added all mods.
      - ./data/config:/data/config:rw,Z

      # Code, *must* be read only so attackers can't inject new code
      - ./data/.cache:/data/.cache:rw,Z  # look into banning permission, likely tmpfs
      - ./data/mods:/data/mods:ro,Z

      # Server data
      ## server must be able to write to these to operate
      - ./data/crash-reports:/data/crash-reports:rw,Z
      - ./data/logs:/data/logs:rw,Z
      - ./data/world:/data/world:rw,Z
      - ./data/banned-ips.json:/data/banned-ips.json:rw,Z
      - ./data/banned-players.json:/data/banned-players.json:rw,Z
      - ./data/ops.json:/data/ops.json:rw,Z
      - ./data/usercache.json:/data/usercache.json:rw,Z
      - ./data/whitelist.json:/data/whitelist.json:rw,Z

    ports:
      # Open default port for minecraft server
      - "25565:25565"

    # Allow us to attach to the container later
    stdin_open: true
    tty: true

    # Protect our entry jar from modification
    read_only: true

    # Java writes and executes from /tmp
    tmpfs:
        - /tmp:size=10M,mode=0770,nosuid,nodev

    # limit the resources that can be used!
    deploy:
      resources:
        limits:
          cpus: 6
          memory: 4g
          pids: 256

    # Drop all capabilities since we don't need them!
    cap_drop:
      - ALL

    # Give it an hour to finish saving the world before quitting
    stop_grace_period: 60m
